# Run as the unprivileged user
user nobody;

# Spawns a worker process per CPU core
worker_processes auto;

# Sets simultaneous users limit per worker
events {
	worker_connections 1024;
}

# Scope: all web traffic
http {
	# MIME types is a dictionary which tells web browser what kind of file it's receiving
	include /etc/nginx/mime.types;
	# Fallback type, raw downloadable binary file
	default_type application/octet-stream;

	# Scope: specific website
	server {
		# Listens on port 443 for IPv4 and IPv6 and expect encrytion
		listen 443 ssl;
		listen [::]:443 ssl;

		# NGINX checks if the URL matches this domain name for processing
		# URL = Uniform Resource Locator
		server_name myli-pen.42.fr;

		# The root directory where WordPress files are
		root /var/www/html;
		# NGINX looks for index in this order when user visits home URL
		index index.php index.html index.htm;

		# SSL configuration, list both TLS versions for backwards compatibility
		ssl_certificate /etc/nginx/ssl/inception.crt;
		ssl_certificate_key /etc/nginx/ssl/inception.key;
		ssl_protocols TLSv1.2 TLSv1.3;

		# NGINX reads based on priority, regex before catch-all

		# Serve static files directly, or fallback to index.php where WP serves appropriate page
		# URI = Uniform Resource Identifier
		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		# Sends .php to the WordPress container
		location ~ \.php$ {
			# Split the URI to handle PHP securely
			fastcgi_split_path_info ^(.+\.php)(/.+)$;

			# Send the request over the network to the wordpress container on port 9000
			fastcgi_pass wordpress:9000;

			fastcgi_index index.php;
			include fastcgi_params;

			# Tell PHP exactly which script to execute
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			fastcgi_param PATH_INFO $fastcgi_path_info;
		}
	}
}
