services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb_image
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_user_password

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: dockerfile
    container_name: wordpress
    image: wordpress_image
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - db_user_password
      - wp_admin_password
      - wp_user_password
    depends_on:
      - mariadb

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx_image
    restart: unless-stopped
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress

networks:
  inception:
    driver: bridge
    name: inception_network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/myli-pen/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/myli-pen/data/wordpress

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_user_password:
    file: ../secrets/db_user_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
